### ISSUE TITLE
msg.message.user.mm.roles.startsWith('system') - undefined roles

### ISSUE THREAD

**Issue by romdim** [shipengqi/sactive-bot#7]
Hey there!

Great repo! Thanks a lot!
I get an error from the filter_middleware.

```
error: TypeError: Cannot read property 'startsWith' of undefined
    at filterMiddleware (/Users/Rtsouroplis/Documents/GitHub/sactive-bot/lib/middlewares/filter_middleware.js:48:72)
    at /Users/Rtsouroplis/Documents/GitHub/sactive-bot/node_modules/hubot/src/middleware.coffee:36:24
    at /Users/Rtsouroplis/Documents/GitHub/sactive-bot/node_modules/async/lib/async.js:269:13
    at iterate (/Users/Rtsouroplis/Documents/GitHub/sactive-bot/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/Users/Rtsouroplis/Documents/GitHub/sactive-bot/node_modules/async/lib/async.js:162:9)
    at Object.async.reduce (/Users/Rtsouroplis/Documents/GitHub/sactive-bot/node_modules/async/lib/async.js:268:15)
    at /Users/Rtsouroplis/Documents/GitHub/sactive-bot/node_modules/hubot/src/middleware.coffee:49:13
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

It doesn't get anything back from `msg.message.user.mm.roles` as it seems.

**Comment by shipengqi** [comment]
> middleware.coffee:36:24

Thanks for your feedback, I have fixed this issue in #8
